#!/usr/bin/env python3
"""Generate `docs/dev/api.md` from the route tables, not by hand.

`organize_archive/web/routes/__init__.py` holds three tables -- `GET_ROUTES`,
`GET_PREFIX_ROUTES`, `POST_ROUTES` -- that are already the single source of
truth for what this server answers (see that module's docstring). A
hand-maintained API doc drifts from those tables the first time someone adds
a route and forgets the doc; a generated one cannot drift, because it *is*
the tables, rendered.

For each route this emits the method, the path (or prefix), the handler's
docstring summary as the description, and `path/to/file.py::function` so
a reader can jump straight to the source. `GET_PREFIX_ROUTES`' declared order
is preserved verbatim -- the first matching prefix wins, so that order is
load-bearing (see `routes/__init__.py`'s docstring) -- and `GET_ROUTES` /
`POST_ROUTES` keep their declared order too, so the doc reads in the same
order as the source file it came from.

Usage:

    python3 tools/dev/gen_api_docs.py            # regenerate docs/dev/api.md
    python3 tools/dev/gen_api_docs.py --check     # CI: fail with a diff if stale

`make api-docs` runs the first form. CI runs the second, after `make lint-py`,
so adding a route without regenerating fails the build instead of leaving a
document that quietly no longer describes the server. It cannot make anyone
*write* a docstring -- a handler without one renders as `*(no docstring)*`,
which is deliberately conspicuous in the table but is not an error.

Importing `organize_archive.web.routes` must stay cheap: no numpy, torch,
onnxruntime, PIL, or any other optional ML dependency at module scope,
because this script (and the CI job that runs it) has no business paying for
face/pet/semantic models just to list endpoints. A couple of handlers
(`pets.summary`, `search.semantic_status`, `search.semantic_search`) defer
their own heavy imports inside the function body for exactly this reason --
this script is one of the reasons that pattern has to hold.
"""

from __future__ import annotations

import argparse
import difflib
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# The repo is not pip-installed into the dev venv -- it is found by being the
# working directory -- and a script's sys.path[0] is its own directory, not the
# cwd. Every tool in tools/ does this for the same reason.
sys.path.insert(0, str(ROOT))

OUT = ROOT / "docs" / "dev" / "api.md"

GENERATE_CMD = ".venv/bin/python tools/dev/gen_api_docs.py"


def _location(handler) -> str:
    """`path/to/file.py::function`, relative to the repo root, so a reader (or an
    editor's "go to definition") can jump straight from the doc to the source."""
    src = Path(inspect.getsourcefile(handler)).resolve()
    return f"{src.relative_to(ROOT)}::{handler.__name__}"


def _description(handler) -> str:
    """The handler's docstring summary -- its first *paragraph*, collapsed onto
    one line, or a visible placeholder if it has none.

    A paragraph rather than a line, because a summary wrapped at 88 columns in
    the source would otherwise be cut mid-sentence in the table. A placeholder
    rather than an empty cell, because a gap that says so is easier to notice
    than a blank that looks deliberate.
    """
    doc = inspect.getdoc(handler)
    if not doc:
        return "*(no docstring)*"
    paragraph = doc.strip().split("\n\n", 1)[0]
    summary = " ".join(line.strip() for line in paragraph.splitlines() if line.strip())
    return summary.replace("|", "\\|")  # keep the markdown table from breaking


def _rows(entries) -> list[str]:
    lines = ["| Path | Description | Handler |", "| --- | --- | --- |"]
    for path, handler in entries:
        lines.append(f"| `{path}` | {_description(handler)} | `{_location(handler)}` |")
    return lines


def generate() -> str:
    """Render the three route tables to a markdown string."""
    # Imported here, not at module scope, so `--check` and the plain-write path
    # both go through one place and a heavy import on the routes side would be
    # obvious from a traceback pointing at this line rather than an opaque one
    # at the top of the script.
    from organize_archive.web import routes

    get_exact = list(routes.GET_ROUTES.items())
    get_prefix = list(routes.GET_PREFIX_ROUTES)
    post = list(routes.POST_ROUTES.items())
    total = len(get_exact) + len(get_prefix) + len(post)

    lines = [
        "# API Reference",
        "",
        "Generated by `tools/dev/gen_api_docs.py` from the three route tables in",
        "`organize_archive/web/routes/__init__.py` -- `GET_ROUTES`, `GET_PREFIX_ROUTES`,",
        "`POST_ROUTES` -- which are already this server's single source of truth for",
        "what it answers. Do not hand-edit this file; regenerate it with:",
        "",
        f"    {GENERATE_CMD}",
        "",
        "or `make api-docs`. CI runs the same script in `--check` mode and fails the",
        "build if this file has drifted from the route tables.",
        "",
        f"**{total} routes**: {len(get_exact)} GET (exact) + {len(get_prefix)} GET"
        f" (prefix) + {len(post)} POST.",
        "",
        "## GET -- exact path",
        "",
        *_rows(get_exact),
        "",
        "## GET -- prefix",
        "",
        "Ordered: exact paths are matched first, then the first matching prefix here",
        "wins. This table keeps that declared order verbatim -- it is load-bearing,",
        "see the module docstring in `routes/__init__.py`.",
        "",
        *_rows(get_prefix),
        "",
        "## POST",
        "",
        *_rows(post),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="don't write anything; exit non-zero with a diff if docs/dev/api.md is stale",
    )
    args = ap.parse_args()

    content = generate()

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current == content:
            print(f"{OUT.relative_to(ROOT)} is up to date")
            return 0
        diff = difflib.unified_diff(
            (current or "").splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=f"{OUT.relative_to(ROOT)} (on disk)",
            tofile=f"{OUT.relative_to(ROOT)} (regenerated)",
        )
        sys.stdout.writelines(diff)
        print(
            f"\n{OUT.relative_to(ROOT)} is stale -- run `{GENERATE_CMD}` (or "
            f"`make api-docs`) and commit the result."
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
